RESULTS_DIR = "results"
ANALYSIS_HISTORY_PATH = "results/analysis_history.csv"
INTERACTIVE_PLOT_PATH = "results/interactive_motif_positions.html"

DEFAULT_SEGMENT_LENGTH = 10
DEFAULT_MOTIFS = "ATG, TATA, CGCG"
HIGHLIGHTED_SEQUENCE_LINE_LENGTH = 80